config settings 'settings'
	# TODO this should be taken fro config.network
	option lan_subnet '192.168.56.2/24'
	# TODO this should be set in GUI
	option token 'secret_token'
	option connect_on_startup '1'
	option connect_string 'LT'
	option meshnet '1'
	option ipv6 '1'
	option log_stderr '1'
	option log_stdout '1'
	